# fly.toml app configuration file generated for laplapv2 on 2026-08-17T12:46:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laplapv2'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'
  [build.args]
    NEXT_PUBLIC_APP_URL = "https://laplapcantho.store"
    NEXT_PUBLIC_SUPABASE_URL = "https://bmvgnhgxbkrhixydsqjh.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_2FmsuicKIKS6liLNmng90A_JYhdm3v_"

[deploy]
  release_command = "node -e \"console.log('Release OK')\""
  strategy = "immediate"

# Env vars NON-SECRET
[env]
  HOSTNAME = "0.0.0.0"
  NEXT_PUBLIC_APP_NAME = "LapLap"
  NEXT_PUBLIC_APP_URL = "https://laplapcantho.store"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  request_body_size_limit = '40mb'

  [http_service.concurrency]
    hard_limit = 200
    soft_limit = 180
    type = 'connections'

  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    timeout = "5s"

# Volume cho file audio
[[mounts]]
destination = "/data/audio"
source = "laplap_audio"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
memory_mb = 512
size = "shared-cpu-1x"
