# fly.toml app configuration file generated for laplapv2 on 2026-08-17T12:46:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laplapv2'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "node -e \"console.log('Release OK')\""

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_APP_URL = "https://laplapcantho.store"
  NEXT_PUBLIC_APP_NAME = "LapLap"
  HOSTNAME = "0.0.0.0"
  NEXT_PUBLIC_SUPABASE_URL="https://bmvgnhgxbkrhixydsqjh.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY="sb_publishable_2FmsuicKIKS6liLNmng90A_JYhdm3v_"
  SUPABASE_SERVICE_ROLE_KEY="sb_secret_8Y26FeVa-kjFTHApuBi-zA_q0vEP7md"
  GEMINI_API_KEY="AIzaSyDhY0bW4j_-MEfl1wMSbNoYjFylRsZGJCo"
  GEMINI_API_KEY_2="AIzaSyD8QiJkkDy_1MkMr-S7nwaKmD0wsSPd_Tc"
  GEMINI_API_KEY_3="AIzaSyBlW51jHU048FvtH5TpWbxrGS23VF4_I9g"
  GEMINI_API_KEY_4="AIzaSyAgHsHrCsObsRr3IjfRhwhLcCIDHX2USo0"
  OPENAI_API_KEY="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"
  TOOLCHECK_BASE_URL="https://pub-7c51a9003fb047ee809178f21148ed17.r2.dev"
  RESEND_API_KEY="re_ALML8UfF_51aVhudQuSkRhj8inFepiSfj"
  RESEND_FROM_EMAIL="LapLap <noreply@laplapcantho.store>"
  CRON_SECRET="b9d21019596a6938356a66d9b63c3a7c4a090ef7858cf405cc842d016db059e1"
  RESEND_WEBHOOK_SECRET="whsec_IYvYWjMv9RMhGxWxLRizVzmdi81AL4aV"
  MINI_TOOL_SHARED_SECRET="f0010cf0aa8f645f80ae7e651d40b5f310e06cdf32b330acae16668648183397"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 200
    soft_limit = 180

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
